version: "3"
services:
  app:
    stdin_open: true
    tty: true
    build: .
    env_file:
      - .vars.env
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
