version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3
      - image: circleci/postgres:10.8-alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: mrbot-development
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run:
          name: Run tests
          command: |
            npm test
          environment:
            ENVIRONMENT: development
            PGHOST: localhost
            PGPORT: 5432
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: mrbot-development


  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Deployment notification to Rollbar
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
            -F access_token=$ROLLBAR_ACCESS_TOKEN \
            -F environment=production \
            -F revision=$CIRCLE_SHA1 \
            -F rollbar_username=mateus.rsnd \
            -F local_username=$CIRCLE_USERNAME

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
