version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - run: npm install
  test:
    docker:
      - image: circleci/node:12.3.1
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
