version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.3
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
      - run:
          name: Deployment notification to Rollbar
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
            -F access_token=$ROLLBAR_ACCESS_TOKEN \
            -F environment=production \
            -F revision=$CIRCLE_SHA1 \
            -F rollbar_username=mateus.rsnd \
            -F local_username=$CIRCLE_USERNAME \
            -F comment='Deploy with bug'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
